spring:
  application:
    name: sample-api
server:
  port: 8081
#  address: 127.0.0.1
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
#    ip-address: ${server.address}
    instance-id: ${spring.application.name}:${spring.application.intance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

